"""
CNN Regime Classifier
Optional 4th MLEnsemble signal: trains a 6-layer 1D CNN on SPY daily OHLCV
to produce a 5-class regime probability vector (STRONG_OVERBOUGHT → STRONG_OVERSOLD).

Enabled via env var REGIME_CNN_ENABLED=true (default: false).
Requires torch (CPU-only build recommended):
  pip install torch==2.3.1+cpu --index-url https://download.pytorch.org/whl/cpu

Architecture (input: batch × 14 features × 30 time-steps):
  Conv1d(14→32, k=3) → BN → ReLU
  Conv1d(32→64, k=3) → BN → ReLU
  Conv1d(64→64, k=3) → BN → ReLU
  AdaptiveAvgPool1d(1) → Flatten → FC(64→32) → ReLU → Dropout(0.3) → FC(32→5)

Labels generated by shared.technical_regime consensus oscillator voting applied
row-by-row with a trailing window — same method as Phase 1, no look-ahead.
"""
import logging
import os
from datetime import date
from typing import Optional

log = logging.getLogger("predictor.regime_cnn")

REGIME_CNN_ENABLED = os.getenv("REGIME_CNN_ENABLED", "false").lower() not in ("false", "0", "no")
HISTORY_DAYS       = 730    # 2 years
SEQ_LEN            = 30     # lookback window for CNN input
EPOCHS             = 50
PATIENCE           = 10
BATCH_SIZE         = 32
LEARNING_RATE      = 1e-3
TRAIN_RATIO        = 0.80

REGIME_CLASSES = [
    "STRONG_OVERSOLD",
    "OVERSOLD",
    "NEUTRAL",
    "OVERBOUGHT",
    "STRONG_OVERBOUGHT",
]

try:
    import numpy as np
    import pandas as pd
    _NUMPY_OK = True
except ImportError:
    _NUMPY_OK = False

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import TensorDataset, DataLoader
    _TORCH_OK = True
except ImportError:
    _TORCH_OK = False
    if REGIME_CNN_ENABLED:
        log.warning("regime_cnn: torch not installed — CNN regime signal disabled")


# ── Feature engineering ───────────────────────────────────────────────────────

def _compute_adx(high: "pd.Series", low: "pd.Series", close: "pd.Series",
                 period: int = 14) -> "pd.Series":
    """Average Directional Index (Wilder smoothing), 0–100 scale."""
    prev_close = close.shift(1)
    tr = pd.concat([
        high - low,
        (high - prev_close).abs(),
        (low  - prev_close).abs(),
    ], axis=1).max(axis=1)

    up   = high - high.shift(1)
    down = low.shift(1) - low
    dm_p = pd.Series(np.where((up > down) & (up > 0), up, 0.0), index=high.index)
    dm_m = pd.Series(np.where((down > up) & (down > 0), down, 0.0), index=low.index)

    atr  = tr.ewm(com=period - 1, min_periods=period).mean()
    di_p = 100 * dm_p.ewm(com=period - 1, min_periods=period).mean() / atr.replace(0, float("nan"))
    di_m = 100 * dm_m.ewm(com=period - 1, min_periods=period).mean() / atr.replace(0, float("nan"))
    denom = (di_p + di_m).replace(0, float("nan"))
    dx   = 100 * (di_p - di_m).abs() / denom
    return dx.ewm(com=period - 1, min_periods=period).mean()


def _engineer_cnn_features(df: "pd.DataFrame") -> "pd.DataFrame":
    """Return a 14-column DataFrame of normalized CNN features aligned to df.index."""
    close  = df["Close"].squeeze()
    high   = df["High"].squeeze()
    low    = df["Low"].squeeze()
    volume = df["Volume"].squeeze()

    f = pd.DataFrame(index=df.index)

    # MACD histogram / price
    ema12 = close.ewm(span=12, adjust=False).mean()
    ema26 = close.ewm(span=26, adjust=False).mean()
    macd  = ema12 - ema26
    sig   = macd.ewm(span=9, adjust=False).mean()
    f["macd_hist"] = (macd - sig) / close.replace(0, float("nan"))

    # Bollinger Band position (-1 to +1)
    sma20 = close.rolling(20).mean()
    std20 = close.rolling(20).std()
    f["bb_pos"] = (close - sma20) / (2 * std20.replace(0, float("nan")))

    # ADX-14
    f["adx"] = _compute_adx(high, low, close, 14) / 100.0

    # ATR%
    hl_range = high - low
    f["atr_pct"] = hl_range.rolling(14).mean() / close.replace(0, float("nan"))

    # OBV normalized
    direction_sign = close.diff().apply(lambda x: 1 if x > 0 else (-1 if x < 0 else 0))
    obv = (volume * direction_sign).cumsum()
    obv_mean = obv.rolling(30).mean().replace(0, float("nan"))
    f["obv_norm"] = obv / obv_mean

    # RSI-14 (0-1)
    delta = close.diff()
    gain  = delta.clip(lower=0).rolling(14).mean()
    loss  = (-delta.clip(upper=0)).rolling(14).mean()
    rs    = gain / loss.replace(0, float("nan"))
    f["rsi_14"] = (100 - 100 / (1 + rs)) / 100.0

    # Williams %R → mapped to 0=OS, 1=OB
    highest = high.rolling(14).max()
    lowest  = low.rolling(14).min()
    denom   = (highest - lowest).replace(0, float("nan"))
    f["williams_r"] = 1.0 - (highest - close) / denom   # 1=OB, 0=OS

    # Stochastic %K (0-1)
    f["stoch_k"] = (close - lowest) / denom

    # MFI (0-1)
    typical = (close + high + low) / 3
    raw_mf  = typical * volume
    pos_mf  = raw_mf.where(typical > typical.shift(1), 0.0)
    neg_mf  = raw_mf.where(typical < typical.shift(1), 0.0)
    pos_sum = pos_mf.rolling(14).sum()
    neg_sum = neg_mf.rolling(14).sum()
    total   = (pos_sum + neg_sum).replace(0, float("nan"))
    f["mfi_14"] = pos_sum / total

    # SMA deviations
    sma50  = close.rolling(50).mean()
    sma200 = close.rolling(200).mean()
    f["sma20_pct"]  = (close - sma20)  / sma20.replace(0, float("nan"))
    f["sma50_pct"]  = (close - sma50)  / sma50.replace(0, float("nan"))
    f["sma200_pct"] = (close - sma200) / sma200.replace(0, float("nan"))

    # Momentum
    f["ret_5"]  = close.pct_change(5)
    f["ret_20"] = close.pct_change(20)

    return f


def _label_rows(df: "pd.DataFrame") -> "pd.Series":
    """
    Assign a 5-class label to each row using the consensus oscillator method
    from shared.technical_regime, applied row-by-row with a 30-bar trailing window.
    No look-ahead: each row only uses bars up to and including itself.
    """
    from shared.technical_regime import compute_technical_regime

    labels = []
    n = len(df)
    for i in range(n):
        window = df.iloc[max(0, i - 29): i + 1]
        bars = [
            {"c": row["Close"], "h": row["High"], "l": row["Low"],
             "o": row["Open"],  "v": row["Volume"]}
            for _, row in window.iterrows()
        ]
        tech = compute_technical_regime(bars)
        regime = tech["technical_regime"]
        labels.append(REGIME_CLASSES.index(regime))

    return pd.Series(labels, index=df.index)


# ── Model ──────────────────────────────────────────────────────────────────────

class RegimeCNN(nn.Module):
    def __init__(self, n_features: int = 14, seq_len: int = SEQ_LEN,
                 n_classes: int = 5):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv1d(n_features, 32, kernel_size=3, padding=1),
            nn.BatchNorm1d(32), nn.ReLU(),
            nn.Conv1d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm1d(64), nn.ReLU(),
            nn.Conv1d(64, 64, kernel_size=3, padding=1),
            nn.BatchNorm1d(64), nn.ReLU(),
        )
        self.pool = nn.AdaptiveAvgPool1d(1)
        self.fc   = nn.Sequential(
            nn.Linear(64, 32), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(32, n_classes),
        )

    def forward(self, x):
        # x: (batch, features, seq_len)
        x = self.conv(x)
        x = self.pool(x).squeeze(-1)   # (batch, 64)
        return self.fc(x)


# ── Training ──────────────────────────────────────────────────────────────────

def _build_sequences(features: "np.ndarray", labels: "np.ndarray",
                     seq_len: int = SEQ_LEN) -> "tuple[np.ndarray, np.ndarray]":
    X, y = [], []
    for i in range(seq_len, len(features)):
        X.append(features[i - seq_len: i].T)   # (features, seq_len)
        y.append(labels[i])
    return np.array(X, dtype=np.float32), np.array(y, dtype=np.int64)


def _train_model(df: "pd.DataFrame") -> "Optional[nn.Module]":
    """Train and return a RegimeCNN on the given OHLCV DataFrame."""
    feat_df  = _engineer_cnn_features(df)
    label_s  = _label_rows(df)

    combined = feat_df.join(label_s.rename("label")).dropna()
    feat_cols = [c for c in combined.columns if c != "label"]

    features = combined[feat_cols].values
    labels   = combined["label"].values

    if len(features) < SEQ_LEN + 50:
        log.warning("regime_cnn: insufficient data (%d rows)", len(features))
        return None

    X, y = _build_sequences(features, labels, SEQ_LEN)

    split  = int(len(X) * TRAIN_RATIO)
    X_tr, X_val = X[:split], X[split:]
    y_tr, y_val = y[:split], y[split:]

    # Class weights (inverse frequency — avoids time-series leakage vs SMOTE)
    counts = np.bincount(y_tr, minlength=5).astype(float)
    counts = np.where(counts == 0, 1.0, counts)
    weights = torch.tensor(1.0 / counts / (1.0 / counts).sum(), dtype=torch.float32)

    model     = RegimeCNN(n_features=len(feat_cols))
    criterion = nn.CrossEntropyLoss(weight=weights)
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=5, factor=0.5)

    train_ds = TensorDataset(torch.from_numpy(X_tr), torch.from_numpy(y_tr))
    train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)

    val_X = torch.from_numpy(X_val)
    val_y = torch.from_numpy(y_val)

    best_val_loss = float("inf")
    best_state    = None
    no_improve    = 0

    for epoch in range(1, EPOCHS + 1):
        model.train()
        for xb, yb in train_dl:
            optimizer.zero_grad()
            loss = criterion(model(xb), yb)
            loss.backward()
            optimizer.step()

        model.eval()
        with torch.no_grad():
            val_loss = criterion(model(val_X), val_y).item()
            preds    = model(val_X).argmax(dim=1)
            val_acc  = (preds == val_y).float().mean().item()

        scheduler.step(val_loss)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state    = {k: v.clone() for k, v in model.state_dict().items()}
            no_improve    = 0
        else:
            no_improve += 1
            if no_improve >= PATIENCE:
                log.info("regime_cnn: early stop at epoch %d val_acc=%.3f", epoch, val_acc)
                break

    if best_state:
        model.load_state_dict(best_state)

    log.info("regime_cnn: training complete val_acc=%.3f val_loss=%.4f rows=%d",
             val_acc, best_val_loss, len(X))
    return model


# ── Inference cache ────────────────────────────────────────────────────────────

_model_cache: dict[date, "nn.Module"] = {}
_probs_cache: dict[date, dict] = {}


def _cache_path(today: date) -> str:
    return f"/tmp/regime_cnn_{today.isoformat()}.pt"


def _fetch_spy_df() -> "Optional[pd.DataFrame]":
    """Fetch SPY OHLCV from market data gateway (synchronous)."""
    import json as _json
    import urllib.request
    gateway = os.getenv("MARKET_DATA_URL", "http://ot-market-data:8090")
    url = f"{gateway}/data/bars/SPY?days={HISTORY_DAYS}&interval=daily"
    with urllib.request.urlopen(url, timeout=30) as resp:
        body = _json.loads(resp.read())
    data = body.get("data", body)
    bars = data if isinstance(data, list) else (
        data.get("bars") or data.get("candles") or data.get("results") or []
    )
    if not bars or len(bars) < SEQ_LEN + 50:
        return None

    rows = []
    for b in bars:
        rows.append({
            "Open":   float(b.get("o") or b.get("open")   or b.get("Open")   or 0),
            "High":   float(b.get("h") or b.get("high")   or b.get("High")   or 0),
            "Low":    float(b.get("l") or b.get("low")    or b.get("Low")    or 0),
            "Close":  float(b.get("c") or b.get("close")  or b.get("Close")  or 0),
            "Volume": float(b.get("v") or b.get("volume") or b.get("Volume") or 0),
        })
    return pd.DataFrame(rows)


def _get_model(today: date) -> "Optional[nn.Module]":
    if today in _model_cache:
        return _model_cache[today]

    path = _cache_path(today)
    if os.path.exists(path):
        try:
            model = RegimeCNN()
            model.load_state_dict(torch.load(path, map_location="cpu", weights_only=True))
            model.eval()
            _model_cache[today] = model
            log.info("regime_cnn: loaded from %s", path)
            return model
        except Exception as e:
            log.warning("regime_cnn: load failed (%s), retraining", e)

    df = _fetch_spy_df()
    if df is None:
        return None

    log.info("regime_cnn: training on %d SPY bars", len(df))
    model = _train_model(df)
    if model is None:
        return None

    model.eval()
    try:
        torch.save(model.state_dict(), path)
    except Exception:
        pass

    _model_cache[today] = model
    return model


def _predict_current_regime(model: "nn.Module", df: "pd.DataFrame") -> dict:
    """Run inference on the most recent SEQ_LEN bars of the feature matrix."""
    feat_df = _engineer_cnn_features(df)
    feat_df = feat_df.dropna()
    if len(feat_df) < SEQ_LEN:
        return {}

    window = feat_df.iloc[-SEQ_LEN:].values.T   # (features, seq_len)
    x = torch.from_numpy(window.astype(np.float32)).unsqueeze(0)   # (1, features, seq_len)

    with torch.no_grad():
        logits = model(x)
        probs  = torch.softmax(logits, dim=1).squeeze(0).tolist()

    regime_idx  = int(torch.tensor(probs).argmax())
    regime_name = REGIME_CLASSES[regime_idx]
    confidence  = probs[regime_idx]

    return {
        "regime":     regime_name,
        "probs":      {REGIME_CLASSES[i]: round(p, 4) for i, p in enumerate(probs)},
        "confidence": round(confidence, 4),
    }


# ── Public API ─────────────────────────────────────────────────────────────────

async def get_spy_regime_probabilities() -> Optional[dict]:
    """
    Async entry point: fetch SPY bars, train/load CNN, return regime probability dict.
    Cached once per calendar day.
    Returns None if disabled or torch unavailable.
    """
    if not REGIME_CNN_ENABLED or not _TORCH_OK or not _NUMPY_OK:
        return None

    today = date.today()
    if today in _probs_cache:
        return _probs_cache[today]

    import asyncio
    try:
        loop  = asyncio.get_event_loop()
        model = await loop.run_in_executor(None, _get_model, today)
        if model is None:
            return None
        df   = await loop.run_in_executor(None, _fetch_spy_df)
        if df is None:
            return None
        result = await loop.run_in_executor(None, _predict_current_regime, model, df)
        if result:
            _probs_cache[today] = result
        return result or None
    except Exception as e:
        log.warning("regime_cnn: prediction failed: %s", e)
        return None


def regime_to_confidence_adjustment(spy_regime: dict, direction: str) -> float:
    """
    Map CNN regime probabilities to a per-ticker confidence delta.
    Uses the probability mass in strong tail classes to scale the adjustment.
    """
    if not spy_regime:
        return 0.0
    probs = spy_regime.get("probs", {})
    if direction == "long":
        pos = probs.get("STRONG_OVERSOLD", 0.0) * 0.15 + probs.get("OVERSOLD", 0.0) * 0.08
        neg = probs.get("STRONG_OVERBOUGHT", 0.0) * 0.15 + probs.get("OVERBOUGHT", 0.0) * 0.08
        return round(pos - neg, 4)
    else:
        pos = probs.get("STRONG_OVERBOUGHT", 0.0) * 0.15 + probs.get("OVERBOUGHT", 0.0) * 0.08
        neg = probs.get("STRONG_OVERSOLD", 0.0) * 0.15 + probs.get("OVERSOLD", 0.0) * 0.08
        return round(pos - neg, 4)
